import { Service, Professional, Product, Appointment, Review, CashFlowTransaction, SalonSettings, SubscriptionSettings } from './types';

export const INITIAL_SALON_SETTINGS: SalonSettings = {
  salonName: 'Studio Juliana Castro Concept',
  ownerName: 'Juliana Castro',
  whatsappNumber: '11987654321',
  phone: '(11) 98765-4321',
  address: 'Alameda Lorena, 1420 - Jardins, São Paulo - SP',
  pixKeyType: 'Celular',
  pixKey: '(11) 98765-4321',
  pixBeneficiary: 'Juliana Castro Cabeleireira ME',
  openingTime: '09:00',
  closingTime: '19:00',
  slotIntervalMinutes: 45,
  openDays: ['Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado'],
  lunchStart: '12:30',
  lunchEnd: '13:30',
};

export const INITIAL_SUBSCRIPTION: SubscriptionSettings = {
  planName: 'Plano Sistema & WhatsApp Pro',
  monthlyPrice: 69.90,
  status: 'Ativo',
  renewalDate: '2026-10-08',
  mercadoPagoPublicKey: 'APP_USR-7a18b2c4-9d03-4e56-8f71-2b83901a8ef1',
  mercadoPagoAccessToken: 'APP_USR-8472910384729103-090812-7bf8103c81034e',
  mercadoPagoPreferenceId: 'pref_sub_julianacastro_2026',
  webhookUrl: 'https://sua-api.antigravity.dev/api/webhooks/mercadopago',
  lastPaymentDate: '2026-09-08',
  paymentHistory: [
    {
      id: 'pay-mp-101',
      date: '2026-09-08',
      amount: 69.90,
      method: 'Mercado Pago PIX Instantâneo',
      status: 'Aprovado',
    },
    {
      id: 'pay-mp-100',
      date: '2026-08-08',
      amount: 69.90,
      method: 'Mercado Pago Cartão de Crédito',
      status: 'Aprovado',
    },
  ],
};

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-1',
    name: 'Corte Visagista & Finalização',
    category: 'Cabelo',
    description: 'Análise de formato de rosto, lavagem especial com massagem capilar, corte personalizado e modelagem.',
    durationMinutes: 50,
    price: 130,
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-2',
    name: 'Mechas Balayage Iluminadas',
    category: 'Coloração',
    description: 'Técnica exclusiva de mechas degradê com efeito natural, tonalização personalizada e tratamento pós-química.',
    durationMinutes: 180,
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-3',
    name: 'Cronograma Capilar de Luxo (Kérastase)',
    category: 'Tratamento',
    description: 'Tratamento profundo com fusio-dose personalizada para nutrição, reparação profunda e brilho espelhado.',
    durationMinutes: 60,
    price: 210,
    imageUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-4',
    name: 'Escova Modelada Glamour',
    category: 'Cabelo',
    description: 'Lavagem com produtos de alta performance, hidratação rápida e escovação com acabamento em ondas.',
    durationMinutes: 45,
    price: 85,
    imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-5',
    name: 'Coloração Global & Banho de Brilho',
    category: 'Coloração',
    description: 'Cobertura total de fios brancos com tintura premium sem amônia, reflexos vibrantes e proteção da fibra.',
    durationMinutes: 90,
    price: 240,
    imageUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-6',
    name: 'Penteado para Noivas & Eventos',
    category: 'Penteado & Noivas',
    description: 'Criação de coques clássicos, tranças desconstruídas ou semi-presos com fixação de alta durabilidade.',
    durationMinutes: 90,
    price: 280,
    imageUrl: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-7',
    name: 'Alinhamento Térmico Orgânico',
    category: 'Tratamento',
    description: 'Redução de volume e frizz com ativos botânicos e aminoácidos, sem formol, garantindo balanço natural.',
    durationMinutes: 120,
    price: 320,
    imageUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'srv-8',
    name: 'Design de Sobrancelhas & Spa Facial',
    category: 'Estética & Barba',
    description: 'Mapeamento facial com linha e pinça, higienização com esfoliação suave e hidratação com máscara calmante.',
    durationMinutes: 40,
    price: 75,
    imageUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=600&q=80',
  }
];

export const INITIAL_PROFESSIONALS: Professional[] = [
  {
    id: 'pro-1',
    name: 'Juliana Castro',
    role: 'Master Hair Stylist, Colorista & Visagista',
    rating: 5.0,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    specialties: ['Balayage & Mechas', 'Cortes Visagistas', 'Tratamentos de Luxo', 'Colorimetria Avançada'],
    phone: '(11) 98765-4321',
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Máscara Kérastase Nutritive Masquintense 200ml',
    brand: 'Kérastase',
    category: 'Máscara',
    description: 'Tratamento nutritivo ultra-concentrado para cabelos ressecados a muito ressecados. Fios macios e aveludados.',
    price: 349.90,
    costPrice: 195.00,
    stock: 8,
    minStockAlert: 3,
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=500&q=80',
    isRetail: true,
  },
  {
    id: 'prod-2',
    name: 'Óleo Capilar L’Oréal Absolut Repair Oil 90ml',
    brand: 'L’Oréal Professionnel',
    category: 'Óleo & Sérum',
    description: 'Óleo restaurador com quinoa dourada e proteína que oferece brilho intenso, toque leve e proteção térmica 230°C.',
    price: 189.00,
    costPrice: 105.00,
    stock: 14,
    minStockAlert: 5,
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-58b8d4e963ee?auto=format&fit=crop&w=500&q=80',
    isRetail: true,
  },
  {
    id: 'prod-3',
    name: 'Shampoo Braé Soul Color 250ml',
    brand: 'Braé',
    category: 'Shampoo',
    description: 'Desenvolvido especialmente para cabelos coloridos e com mechas. Higieniza com suavidade sem desbotar o tom.',
    price: 119.90,
    costPrice: 62.00,
    stock: 12,
    minStockAlert: 4,
    imageUrl: 'https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=500&q=80',
    isRetail: true,
  },
  {
    id: 'prod-4',
    name: 'Spray Leave-in Wella Professionals Miracle 150ml',
    brand: 'Wella',
    category: 'Finalizador',
    description: 'Tratamento leave-in multi-benefícios: desembaraça em 90 segundos, bloqueia a umidade e previne quebra.',
    price: 165.00,
    costPrice: 89.00,
    stock: 2, // Low stock on purpose to trigger alert!
    minStockAlert: 5,
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=500&q=80',
    isRetail: true,
  },
  {
    id: 'prod-5',
    name: 'Kit Tratamento Reconstrutor Olaplex No. 3, 4 e 5',
    brand: 'Olaplex',
    category: 'Kit',
    description: 'Sistema completo patenteado de restauração das pontes de dissulfeto para fios descoloridos e danificados.',
    price: 520.00,
    costPrice: 310.00,
    stock: 5,
    minStockAlert: 2,
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=500&q=80',
    isRetail: true,
  },
  {
    id: 'prod-6',
    name: 'Pó Descolorante Blond Studio 9 Tons 500g (Uso Interno)',
    brand: 'L’Oréal Professionnel',
    category: 'Máscara',
    description: 'Uso exclusivo profissional em salão. Clareamento ultra-rápido com protetor de fibra integrado.',
    price: 260.00,
    costPrice: 175.00,
    stock: 3,
    minStockAlert: 4, // low stock!
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=500&q=80',
    isRetail: false,
  },
  {
    id: 'prod-7',
    name: 'Oxidante Cremoso 20 Volumes 1000ml (Uso Interno)',
    brand: 'Wella Welloxon',
    category: 'Finalizador',
    description: 'Emulsão reveladora estabilizada para colorações permanentes e descolorações perfeitas.',
    price: 95.00,
    costPrice: 48.00,
    stock: 7,
    minStockAlert: 3,
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-58b8d4e963ee?auto=format&fit=crop&w=500&q=80',
    isRetail: false,
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    clientName: 'Fernanda Vasconcelos',
    clientPhone: '11987654321',
    clientEmail: 'fernanda.v@gmail.com',
    serviceId: 'srv-2',
    serviceName: 'Mechas Balayage Iluminadas',
    servicePrice: 420,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-08',
    time: '09:30',
    status: 'Confirmado',
    notes: 'Prefere mechas no tom mel e dourado.',
    whatsappReminderSent: true,
    confirmedAt: '2026-09-07T09:15:00',
    createdAt: '2026-09-05T14:20:00',
  },
  {
    id: 'apt-102',
    clientName: 'Mariana Lima Santos',
    clientPhone: '11977778899',
    clientEmail: 'mari.lima@hotmail.com',
    serviceId: 'srv-1',
    serviceName: 'Corte Visagista & Finalização',
    servicePrice: 130,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-08',
    time: '14:00',
    status: 'Pendente',
    notes: 'Transição capilar recente.',
    whatsappReminderSent: false,
    createdAt: '2026-09-06T10:00:00',
  },
  {
    id: 'apt-103',
    clientName: 'Beatriz Costa',
    clientPhone: '11999887766',
    clientEmail: 'bia.costa@outlook.com',
    serviceId: 'srv-3',
    serviceName: 'Cronograma Capilar de Luxo (Kérastase)',
    servicePrice: 210,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-08',
    time: '16:00',
    status: 'Confirmado',
    notes: 'Cabelos secos por exposição solar.',
    whatsappReminderSent: true,
    confirmedAt: '2026-09-07T10:00:00',
    createdAt: '2026-09-04T18:30:00',
  },
  {
    id: 'apt-104',
    clientName: 'Patrícia Prado',
    clientPhone: '11988223344',
    clientEmail: 'patricia.prado@gmail.com',
    serviceId: 'srv-6',
    serviceName: 'Penteado para Noivas & Eventos',
    servicePrice: 280,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-09',
    time: '11:00',
    status: 'Pendente',
    notes: 'Madrinha de casamento às 17h.',
    whatsappReminderSent: false,
    createdAt: '2026-09-06T17:45:00',
  },
  {
    id: 'apt-105',
    clientName: 'Ana Clara Nogueira',
    clientPhone: '11971234567',
    clientEmail: 'anaclara@gmail.com',
    serviceId: 'srv-1',
    serviceName: 'Corte Visagista & Finalização',
    servicePrice: 130,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-05',
    time: '10:00',
    status: 'Concluído',
    notes: 'Corte long bob com camadas leves.',
    whatsappReminderSent: true,
    confirmedAt: '2026-09-04T11:00:00',
    createdAt: '2026-09-02T09:00:00',
    reviewed: true,
  },
  {
    id: 'apt-106',
    clientName: 'Larissa Moura',
    clientPhone: '11993456789',
    clientEmail: 'larissa.moura@uol.com.br',
    serviceId: 'srv-7',
    serviceName: 'Alinhamento Térmico Orgânico',
    servicePrice: 320,
    professionalId: 'pro-1',
    professionalName: 'Juliana Castro',
    date: '2026-09-04',
    time: '15:00',
    status: 'Concluído',
    whatsappReminderSent: true,
    confirmedAt: '2026-09-03T16:20:00',
    createdAt: '2026-09-01T15:00:00',
    reviewed: true,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    clientName: 'Ana Clara Nogueira',
    rating: 5,
    comment: 'A Juliana foi sensacional! Entendeu perfeitamente o corte que eu queria e deu várias dicas de manutenção. O salão é impecável e o café é maravilhoso.',
    serviceName: 'Corte Visagista & Finalização',
    professionalName: 'Juliana Castro',
    date: '2026-09-05',
    verifiedBooking: true,
  },
  {
    id: 'rev-2',
    clientName: 'Larissa Moura',
    rating: 5,
    comment: 'Fiz o alinhamento orgânico com a Camila e meu cabelo nunca esteve tão brilhoso e macio, sem cheiro forte nenhum! Atendimento de rainha.',
    serviceName: 'Alinhamento Térmico Orgânico',
    professionalName: 'Camila Albuquerque',
    date: '2026-09-04',
    verifiedBooking: true,
  },
  {
    id: 'rev-3',
    clientName: 'Carolina Mendes',
    rating: 5,
    comment: 'O lembrete que recebi no WhatsApp foi ótimo para não me esquecer do horário e confirmei em um toque. Super organizado e pontual!',
    serviceName: 'Mechas Balayage Iluminadas',
    professionalName: 'Juliana Castro',
    date: '2026-09-02',
    verifiedBooking: true,
  },
  {
    id: 'rev-4',
    clientName: 'Renata Albuquerque',
    rating: 4,
    comment: 'Rodrigo arrasa no corte! Muito detalhista e atencioso. Super recomendo a escova modelada também.',
    serviceName: 'Corte Visagista & Finalização',
    professionalName: 'Rodrigo Medeiros',
    date: '2026-08-28',
    verifiedBooking: true,
  }
];

export const INITIAL_TRANSACTIONS: CashFlowTransaction[] = [
  {
    id: 'tx-1',
    date: '2026-09-01',
    description: 'Pagamento Aluguel do Ponto Comercial',
    category: 'Aluguel & Contas',
    type: 'Saída',
    amount: 3500,
    paymentMethod: 'PIX',
  },
  {
    id: 'tx-2',
    date: '2026-09-02',
    description: 'Reposição Estoque Linha Kérastase & L’Oréal',
    category: 'Estoque',
    type: 'Saída',
    amount: 2450,
    paymentMethod: 'Boleto',
  },
  {
    id: 'tx-3',
    date: '2026-09-03',
    description: 'Conta de Energia Elétrica e Água',
    category: 'Aluguel & Contas',
    type: 'Saída',
    amount: 890,
    paymentMethod: 'PIX',
  },
  {
    id: 'tx-4',
    date: '2026-09-04',
    description: 'Atendimento Alinhamento Térmico - Larissa Moura',
    category: 'Serviço',
    type: 'Entrada',
    amount: 320,
    paymentMethod: 'Cartão de Crédito',
    referenceId: 'apt-106',
  },
  {
    id: 'tx-5',
    date: '2026-09-05',
    description: 'Atendimento Corte Visagista - Ana Clara',
    category: 'Serviço',
    type: 'Entrada',
    amount: 130,
    paymentMethod: 'PIX',
    referenceId: 'apt-105',
  },
  {
    id: 'tx-6',
    date: '2026-09-05',
    description: 'Venda Loja: Máscara Kérastase + Óleo L’Oréal',
    category: 'Venda de Produto',
    type: 'Entrada',
    amount: 538.90,
    paymentMethod: 'Cartão de Crédito',
  },
  {
    id: 'tx-7',
    date: '2026-09-06',
    description: 'Adiantamento de Comissão - Juliana Castro',
    category: 'Comissões',
    type: 'Saída',
    amount: 1200,
    paymentMethod: 'PIX',
  },
  {
    id: 'tx-8',
    date: '2026-09-06',
    description: 'Venda Loja: Kit Olaplex No. 3, 4 e 5',
    category: 'Venda de Produto',
    type: 'Entrada',
    amount: 520.00,
    paymentMethod: 'PIX',
  },
  {
    id: 'tx-9',
    date: '2026-09-07',
    description: 'Venda Loja: Shampoo Braé Soul Color',
    category: 'Venda de Produto',
    type: 'Entrada',
    amount: 119.90,
    paymentMethod: 'PIX',
  },
  {
    id: 'tx-10',
    date: '2026-09-07',
    description: 'Serviços Diversos Dia 07/09',
    category: 'Serviço',
    type: 'Entrada',
    amount: 980,
    paymentMethod: 'Cartão de Débito',
  }
];
